In [1]:
from konlpy.tag import Okt
import pandas as pd
import numpy as np

In [2]:
import os

def read_data(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        data = f.read()
        # remove_quotes
        data = data.replace("‘", " ")
        data = data.replace("’", " ")
        data = data.replace("“", " ")
        data = data.replace("”", " ")
        data = data.replace("`", " ")
        data = data.replace("\'", " ")
        data = data.replace("\"", " ")
    return data


global_data = read_data('dataset/keywords/global.csv')
active_data = read_data('dataset/keywords/active.csv')
challenge_data = read_data('dataset/keywords/challenge.csv')
sincerity_data = read_data('dataset/keywords/sincerity.csv')
communication_data = read_data('dataset/keywords/communication.csv')
patient_data = read_data('dataset/keywords/patient.csv')
honesty_data = read_data('dataset/keywords/honesty.csv')
responsibility_data = read_data('dataset/keywords/responsibility.csv')
creative_data = read_data('dataset/keywords/creative.csv')
teamwork_data = read_data('dataset/keywords/teamwork.csv')

In [3]:
import csv

pd.options.mode.chained_assignment = None
np.random.seed(0)

# Kolnpy
okt = Okt()

rawdata = [
    global_data,
    active_data,
    challenge_data,
    sincerity_data,
    communication_data,
    patient_data,
    honesty_data,
    responsibility_data,
    creative_data,
    teamwork_data
]

keyword_names = ['글로벌역량', '능동', '도전', '성실', '소통', '인내심', '정직', '주인의식', '창의', '팀워크']

# 불용어리스트 불러오는 과정
f = open('dataset/stopwords/stopwords.csv', 'r', encoding='utf-8')
reader = csv.reader(f)
stopwords = list()

for row in reader:
    stopwords.append(row[0])

In [4]:
# raw한 문장데이터를 분석에 알맞게 정제하도록 한다.
def tokenizer(raw, pos=["Noun","Verb"], stopword=stopwords):
    return [
        word for word, tag in okt.pos(
            raw, 
            norm=True,   # normalize 정제 과정
            stem=True    # stemming 정제 과정
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [5]:
global_csv = pd.read_csv('dataset/keywords/global.csv', encoding="utf-8")
active_csv = pd.read_csv('dataset/keywords/active.csv', encoding="utf-8")
challenge_csv = pd.read_csv('dataset/keywords/challenge.csv', encoding="utf-8")
sincerity_csv = pd.read_csv('dataset/keywords/sincerity.csv', encoding="utf-8")
communication_csv = pd.read_csv('dataset/keywords/communication.csv', encoding="utf-8")
patient_csv = pd.read_csv('dataset/keywords/patient.csv', encoding="utf-8")
honesty_csv = pd.read_csv('dataset/keywords/honesty.csv', encoding="utf-8")
responsibility_csv = pd.read_csv('dataset/keywords/responsibility.csv', encoding="utf-8")
creative_csv = pd.read_csv('dataset/keywords/creative.csv', encoding="utf-8")
teamwork_csv = pd.read_csv('dataset/keywords/teamwork.csv', encoding="utf-8")

In [6]:
global_csv.head()

                                                  문장
0        "페이스북 나와!"...네이버 라인, 일본 거점으로 글로벌 블록체인 시장 공략
1  ■’룰 세팅’ 완료된 일본 라이센스 기반으로 해외공략 특히 라인은 글로벌 소셜네트워...
2              FAO 한국사무소, 종로에 문 연다…식량·농업 외교 역량 강화 기대
3  FAO는 13일 서울 종로구 글로벌센터 빌딩에서 한국협력연락사무소 개소식을 갖는다....
4  [글로벌-Biz 24] KIND-현대엔지니어링 협력해 1조3천억 폴란드 석유화학플랜...

In [7]:
global_csv["문장"]

0           "페이스북 나와!"...네이버 라인, 일본 거점으로 글로벌 블록체인 시장 공략
1     ■’룰 세팅’ 완료된 일본 라이센스 기반으로 해외공략 특히 라인은 글로벌 소셜네트워...
2                 FAO 한국사무소, 종로에 문 연다…식량·농업 외교 역량 강화 기대
3     FAO는 13일 서울 종로구 글로벌센터 빌딩에서 한국협력연락사무소 개소식을 갖는다....
4     [글로벌-Biz 24] KIND-현대엔지니어링 협력해 1조3천억 폴란드 석유화학플랜...
5     발휘함으로써 '팀코리아'의 역량을 입증한 대표적 사례"라고 말했다. 폴란드 수도 바...
6                          다날, 수익성장-신사업 확대 위해 '조직역량 강화'
7     관계자는 "4차산업혁명에 대응하는 로봇기술, 빅데이터, 블록체인 기술에 투자와 M&...
8                      여수 한영대학, 교육부 전문대학혁신지원사업 역량강화형 선정
9     여수 한영대학(총장 임정섭)은 최근 교육부에서 주관하는 '2019 전문대학혁신지원사...
10    동원과학기술대학교가 서원유통과 동원과학기술대학교 3층 소회의실에서 상호협력을 통한 ...
11                                 양질의 취업 위한 학생 역량강화 노력
12                         은행들 '디지털·글로벌 인력' 대대적 '육성' 경쟁
13    디지털 역량을 강화한다. 지난 7일에는 서울과학종합대학원과 업무협약(MOU)을 맺고...
14            대구시, '인재양성''과 '글로벌 네트워크 강화'로 로봇 도시 위상 높인다
15    지금까지 1천800여 명이 로봇 제조 및 생산실무 전문기술·기능 교육과 역량강화 교...
16                 [신아-50대기업 해부8] 한화그룹, 글로벌 기업 도약 '정조준'
17    각 기업은 시대가 요구하는 변화에 대응하기 위해 핵심 사업의 역량을 끌어올리는가 하...
18         베어링독일펀드, ‘유럽 성장엔진’ 독일에 베팅… 글로벌 경기회복시 최대 수...
19    경험과 역량을 보유한 경영진, 경쟁력 있는 프랜차이즈, 건전한 재무구조 등을 가진 ...
Name: 문장, dtype: object

In [8]:
global_csv = pd.DataFrame(global_csv["문장"])
global_csv["label"] = 1
active_csv = pd.DataFrame(global_csv["문장"])
active_csv["label"] = 2
challenge_csv = pd.DataFrame(global_csv["문장"])
challenge_csv["label"] = 3
sincerity_csv = pd.DataFrame(global_csv["문장"])
sincerity_csv["label"] = 4
communication_csv = pd.DataFrame(global_csv["문장"])
communication_csv["label"] = 5
patient_csv = pd.DataFrame(global_csv["문장"])
patient_csv["label"] = 6
honesty_csv = pd.DataFrame(global_csv["문장"])
honesty_csv["label"] = 7
responsibility_csv = pd.DataFrame(global_csv["문장"])
responsibility_csv["label"] = 8
creative_csv = pd.DataFrame(global_csv["문장"])
creative_csv["label"] = 9
teamwork_csv = pd.DataFrame(global_csv["문장"])
teamwork_csv["label"] = 10

In [9]:
global_csv

                                                   문장  label
0         "페이스북 나와!"...네이버 라인, 일본 거점으로 글로벌 블록체인 시장 공략      1
1   ■’룰 세팅’ 완료된 일본 라이센스 기반으로 해외공략 특히 라인은 글로벌 소셜네트워...      1
2               FAO 한국사무소, 종로에 문 연다…식량·농업 외교 역량 강화 기대      1
3   FAO는 13일 서울 종로구 글로벌센터 빌딩에서 한국협력연락사무소 개소식을 갖는다....      1
4   [글로벌-Biz 24] KIND-현대엔지니어링 협력해 1조3천억 폴란드 석유화학플랜...      1
5   발휘함으로써 '팀코리아'의 역량을 입증한 대표적 사례"라고 말했다. 폴란드 수도 바...      1
6                        다날, 수익성장-신사업 확대 위해 '조직역량 강화'      1
7   관계자는 "4차산업혁명에 대응하는 로봇기술, 빅데이터, 블록체인 기술에 투자와 M&...      1
8                    여수 한영대학, 교육부 전문대학혁신지원사업 역량강화형 선정      1
9   여수 한영대학(총장 임정섭)은 최근 교육부에서 주관하는 '2019 전문대학혁신지원사...      1
10  동원과학기술대학교가 서원유통과 동원과학기술대학교 3층 소회의실에서 상호협력을 통한 ...      1
11                               양질의 취업 위한 학생 역량강화 노력      1
12                       은행들 '디지털·글로벌 인력' 대대적 '육성' 경쟁      1
13  디지털 역량을 강화한다. 지난 7일에는 서울과학종합대학원과 업무협약(MOU)을 맺고...      1
14          대구시, '인재양성''과 '글로벌 네트워크 강화'로 로봇 도시 위상 높인다      1
15  지금까지 1천800여 명이 로봇 제조 및 생산실무 전문기술·기능 교육과 역량강화 교...      1
16               [신아-50대기업 해부8] 한화그룹, 글로벌 기업 도약 '정조준'      1
17  각 기업은 시대가 요구하는 변화에 대응하기 위해 핵심 사업의 역량을 끌어올리는가 하...      1
18       베어링독일펀드, ‘유럽 성장엔진’ 독일에 베팅… 글로벌 경기회복시 최대 수...      1
19  경험과 역량을 보유한 경영진, 경쟁력 있는 프랜차이즈, 건전한 재무구조 등을 가진 ...      1

In [10]:
all_data = global_csv.append(active_csv).append(challenge_csv).append(sincerity_csv).append(communication_csv)
all_data = all_data.append(patient_csv).append(honesty_csv).append(responsibility_csv).append(creative_csv).append(teamwork_csv)

In [11]:
all_data

                                                   문장  label
0         "페이스북 나와!"...네이버 라인, 일본 거점으로 글로벌 블록체인 시장 공략      1
1   ■’룰 세팅’ 완료된 일본 라이센스 기반으로 해외공략 특히 라인은 글로벌 소셜네트워...      1
2               FAO 한국사무소, 종로에 문 연다…식량·농업 외교 역량 강화 기대      1
3   FAO는 13일 서울 종로구 글로벌센터 빌딩에서 한국협력연락사무소 개소식을 갖는다....      1
4   [글로벌-Biz 24] KIND-현대엔지니어링 협력해 1조3천억 폴란드 석유화학플랜...      1
5   발휘함으로써 '팀코리아'의 역량을 입증한 대표적 사례"라고 말했다. 폴란드 수도 바...      1
6                        다날, 수익성장-신사업 확대 위해 '조직역량 강화'      1
7   관계자는 "4차산업혁명에 대응하는 로봇기술, 빅데이터, 블록체인 기술에 투자와 M&...      1
8                    여수 한영대학, 교육부 전문대학혁신지원사업 역량강화형 선정      1
9   여수 한영대학(총장 임정섭)은 최근 교육부에서 주관하는 '2019 전문대학혁신지원사...      1
10  동원과학기술대학교가 서원유통과 동원과학기술대학교 3층 소회의실에서 상호협력을 통한 ...      1
11                               양질의 취업 위한 학생 역량강화 노력      1
12                       은행들 '디지털·글로벌 인력' 대대적 '육성' 경쟁      1
13  디지털 역량을 강화한다. 지난 7일에는 서울과학종합대학원과 업무협약(MOU)을 맺고...      1
14          대구시, '인재양성''과 '글로벌 네트워크 강화'로 로봇 도시 위상 높인다      1
15  지금까지 1천800여 명이 로봇 제조 및 생산실무 전문기술·기능 교육과 역량강화 교...      1
16               [신아-50대기업 해부8] 한화그룹, 글로벌 기업 도약 '정조준'      1
17  각 기업은 시대가 요구하는 변화에 대응하기 위해 핵심 사업의 역량을 끌어올리는가 하...      1
18       베어링독일펀드, ‘유럽 성장엔진’ 독일에 베팅… 글로벌 경기회복시 최대 수...      1
19  경험과 역량을 보유한 경영진, 경쟁력 있는 프랜차이즈, 건전한 재무구조 등을 가진 ...      1
0         "페이스북 나와!"...네이버 라인, 일본 거점으로 글로벌 블록체인 시장 공략      2
1   ■’룰 세팅’ 완료된 일본 라이센스 기반으로 해외공략 특히 라인은 글로벌 소셜네트워...      2
2               FAO 한국사무소, 종로에 문 연다…식량·농업 외교 역량 강화 기대      2
3   FAO는 13일 서울 종로구 글로벌센터 빌딩에서 한국협력연락사무소 개소식을 갖는다....      2
4   [글로벌-Biz 24] KIND-현대엔지니어링 협력해 1조3천억 폴란드 석유화학플랜...      2
5   발휘함으로써 '팀코리아'의 역량을 입증한 대표적 사례"라고 말했다. 폴란드 수도 바...      2
6                        다날, 수익성장-신사업 확대 위해 '조직역량 강화'      2
7   관계자는 "4차산업혁명에 대응하는 로봇기술, 빅데이터, 블록체인 기술에 투자와 M&...      2
8                    여수 한영대학, 교육부 전문대학혁신지원사업 역량강화형 선정      2
9   여수 한영대학(총장 임정섭)은 최근 교육부에서 주관하는 '2019 전문대학혁신지원사...      2
..                                                ...    ...
10  동원과학기술대학교가 서원유통과 동원과학기술대학교 3층 소회의실에서 상호협력을 통한 ...      9
11                               양질의 취업 위한 학생 역량강화 노력      9
12                       은행들 '디지털·글로벌 인력' 대대적 '육성' 경쟁      9
13  디지털 역량을 강화한다. 지난 7일에는 서울과학종합대학원과 업무협약(MOU)을 맺고...      9
14          대구시, '인재양성''과 '글로벌 네트워크 강화'로 로봇 도시 위상 높인다      9
15  지금까지 1천800여 명이 로봇 제조 및 생산실무 전문기술·기능 교육과 역량강화 교...      9
16               [신아-50대기업 해부8] 한화그룹, 글로벌 기업 도약 '정조준'      9
17  각 기업은 시대가 요구하는 변화에 대응하기 위해 핵심 사업의 역량을 끌어올리는가 하...      9
18       베어링독일펀드, ‘유럽 성장엔진’ 독일에 베팅… 글로벌 경기회복시 최대 수...      9
19  경험과 역량을 보유한 경영진, 경쟁력 있는 프랜차이즈, 건전한 재무구조 등을 가진 ...      9
0         "페이스북 나와!"...네이버 라인, 일본 거점으로 글로벌 블록체인 시장 공략     10
1   ■’룰 세팅’ 완료된 일본 라이센스 기반으로 해외공략 특히 라인은 글로벌 소셜네트워...     10
2               FAO 한국사무소, 종로에 문 연다…식량·농업 외교 역량 강화 기대     10
3   FAO는 13일 서울 종로구 글로벌센터 빌딩에서 한국협력연락사무소 개소식을 갖는다....     10
4   [글로벌-Biz 24] KIND-현대엔지니어링 협력해 1조3천억 폴란드 석유화학플랜...     10
5   발휘함으로써 '팀코리아'의 역량을 입증한 대표적 사례"라고 말했다. 폴란드 수도 바...     10
6                        다날, 수익성장-신사업 확대 위해 '조직역량 강화'     10
7   관계자는 "4차산업혁명에 대응하는 로봇기술, 빅데이터, 블록체인 기술에 투자와 M&...     10
8                    여수 한영대학, 교육부 전문대학혁신지원사업 역량강화형 선정     10
9   여수 한영대학(총장 임정섭)은 최근 교육부에서 주관하는 '2019 전문대학혁신지원사...     10
10  동원과학기술대학교가 서원유통과 동원과학기술대학교 3층 소회의실에서 상호협력을 통한 ...     10
11                               양질의 취업 위한 학생 역량강화 노력     10
12                       은행들 '디지털·글로벌 인력' 대대적 '육성' 경쟁     10
13  디지털 역량을 강화한다. 지난 7일에는 서울과학종합대학원과 업무협약(MOU)을 맺고...     10
14          대구시, '인재양성''과 '글로벌 네트워크 강화'로 로봇 도시 위상 높인다     10
15  지금까지 1천800여 명이 로봇 제조 및 생산실무 전문기술·기능 교육과 역량강화 교...     10
16               [신아-50대기업 해부8] 한화그룹, 글로벌 기업 도약 '정조준'     10
17  각 기업은 시대가 요구하는 변화에 대응하기 위해 핵심 사업의 역량을 끌어올리는가 하...     10
18       베어링독일펀드, ‘유럽 성장엔진’ 독일에 베팅… 글로벌 경기회복시 최대 수...     10
19  경험과 역량을 보유한 경영진, 경쟁력 있는 프랜차이즈, 건전한 재무구조 등을 가진 ...     10

[200 rows x 2 columns]

In [12]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(all_data, test_size=0.33, random_state=42)
train["label"] = pd.Categorical(train["label"])

In [13]:
train.groupby("label").count()

       문장
label
1      13
2      14
3      17
4       9
5      12
6      15
7      12
8      14
9      12
10     16

In [14]:
test.groupby("label").count()

       문장
label
1       7
2       6
3       3
4      11
5       8
6       5
7       8
8       6
9       8
10      4

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorize = TfidfVectorizer(
    ngram_range=(1,2),
    tokenizer=tokenizer,
    max_df=0.95,
    min_df=0,
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)

In [16]:
tdm = vectorize.fit_transform(train["문장"])

In [17]:
vectorize.vocabulary_

{'한국': 457,
 '사무소': 207,
 '종로': 373,
 '식량': 268,
 '농업': 107,
 '외교': 310,
 '역량': 292,
 '강화': 4,
 '기대': 77,
 '한국 사무소': 458,
 '사무소 종로': 211,
 '종로 식량': 374,
 '식량 농업': 269,
 '농업 외교': 109,
 '외교 역량': 311,
 '역량 강화': 293,
 '강화 기대': 6,
 '여수': 289,
 '대학': 129,
 '총장': 399,
 '임정섭': 346,
 '최근': 401,
 '교육부': 47,
 '주관': 379,
 '하다': 437,
 '전문': 358,
 '혁신': 471,
 '지원': 390,
 '사업': 212,
 '유형': 329,
 '글로벌': 61,
 '인재': 338,
 '육성': 331,
 '지역': 387,
 '전략': 356,
 '사업인': 216,
 '석유화학': 236,
 '산업': 222,
 '수요': 255,
 '맞추다': 170,
 '여수 대학': 290,
 '대학 총장': 132,
 '총장 임정섭': 400,
 '임정섭 최근': 347,
 '최근 교육부': 402,
 '교육부 주관': 49,
 '주관 하다': 380,
 '하다 전문': 446,
 '전문 대학': 360,
 '대학 혁신': 133,
 '혁신 지원': 473,
 '지원 사업': 391,
 '사업 역량': 213,
 '강화 유형': 11,
 '유형 혁신': 330,
 '혁신 글로벌': 472,
 '글로벌 인재': 72,
 '인재 육성': 340,
 '육성 하다': 333,
 '하다 하다': 450,
 '하다 지역': 448,
 '지역 전략': 388,
 '전략 사업인': 357,
 '사업인 여수': 217,
 '여수 석유화학': 291,
 '석유화학 산업': 237,
 '산업 수요': 223,
 '수요 맞추다': 256,
 '동원과학기술대': 143,
 '학교': 452,
 '유통': 327,
 '회의실': 493,
 '상호': 228,
 '협력': 478,
 '통한': 414,
 '양성': 276,
 '시설': 263,
 '전체': 361,
 '동원과학기술대 학교': 144,
 '학교 유통': 453,
 '유통 동원과학기술대': 328,
 '학교 회의실': 454,
 '회의실 상호': 494,
 '상호 협력': 229,
 '협력 통한': 480,
 '통한 글로벌': 415,
 '인재 양성': 339,
 '양성 역량': 278,
 '강화 대학': 8,
 '대학 시설': 131,
 '시설 전체': 264,
 '전체 지역': 362,
 '지역 하다': 389,
 '하다 대학': 439,
 '신아': 270,
 '대기업': 119,
 '해부': 463,
 '한화': 460,
 '그룹': 54,
 '기업': 84,
 '도약': 138,
 '조준': 369,
 '신아 대기업': 271,
 '대기업 해부': 120,
 '해부 한화': 464,
 '한화 그룹': 461,
 '그룹 글로벌': 55,
 '글로벌 기업': 65,
 '기업 도약': 85,
 '도약 조준': 139,
 '양질': 280,
 '취업': 404,
 '학생': 455,
 '노력': 104,
 '양질 취업': 281,
 '취업 학생': 405,
 '학생 역량': 456,
 '강화 노력': 7,
 '관계자': 41,
 '산업혁명': 225,
 '대응': 121,
 '로봇': 160,
 '기술': 80,
 '빅데이터': 201,
 '블록': 199,
 '체인': 396,
 '투자': 418,
 '늘다': 111,
 '지속': 385,
 '확보': 488,
 '통해': 416,
 '결제': 20,
 '시장': 265,
 '리더': 166,
 '로서': 164,
 '위치': 318,
 '공고': 33,
 '나가다': 94,
 '관계자 산업혁명': 42,
 '산업혁명 대응': 226,
 '대응 하다': 122,
 '하다 로봇': 440,
 '로봇 기술': 161,
 '기술 빅데이터': 82,
 '빅데이터 블록': 202,
 '블록 체인': 200,
 '체인 기술': 397,
 '기술 투자': 83,
 '투자 늘다': 419,
 '늘다 지속': 114,
 '지속 인재': 386,
 '인재 확보': 342,
 '확보 통해': 489,
 '통해 그룹': 417,
 '그룹 역량': 56,
 '역량 글로벌': 294,
 '글로벌 결제': 62,
 '결제 시장': 21,
 '시장 리더': 267,
 '리더 로서': 167,
 '로서 위치': 165,
 '위치 공고': 319,
 '공고 나가다': 34,
 '나가다 하다': 95,
 '세팅': 247,
 '완료': 308,
 '되다': 147,
 '일본': 343,
 '라이센스': 155,
 '기반': 78,
 '해외': 465,
 '공략': 35,
 '라인': 157,
 '소셜네트워크서비스': 251,
 '페이스북': 425,
 '기존': 88,
 '서비스': 232,
 '월간': 314,
 '사용자': 218,
 '적지': 354,
 '모바일': 175,
 '메신저': 173,
 '테크': 412,
 '업계': 282,
 '세팅 완료': 248,
 '완료 되다': 309,
 '되다 일본': 148,
 '일본 라이센스': 345,
 '라이센스 기반': 156,
 '기반 해외': 79,
 '해외 공략': 466,
 '공략 라인': 36,
 '라인 글로벌': 158,
 '글로벌 소셜네트워크서비스': 70,
 '소셜네트워크서비스 페이스북': 252,
 '페이스북 기존': 426,
 '기존 서비스': 89,
 '서비스 월간': 233,
 '월간 사용자': 315,
 '사용자 늘다': 219,
 '늘다 적지': 113,
 '적지 모바일': 355,
 '모바일 메신저': 176,
 '메신저 테크': 174,
 '테크 역량': 413,
 '역량 업계': 297,
 '베어링': 187,
 '독일': 140,
 '펀드': 423,
 '유럽': 323,
 '성장': 242,
 '엔진': 287,
 '베팅': 189,
 '경기': 22,
 '회복': 491,
 '최대': 403,
 '베어링 독일': 188,
 '독일 펀드': 142,
 '펀드 유럽': 424,
 '유럽 성장': 324,
 '성장 엔진': 244,
 '엔진 독일': 288,
 '독일 베팅': 141,
 '베팅 글로벌': 190,
 '글로벌 경기': 63,
 '경기 회복': 24,
 '회복 최대': 492,
 '디지털': 152,
 '지난': 381,
 '과학': 39,
 '종합대학': 377,
 '업무': 283,
 '협약': 484,
 '맺다': 171,
 '데이터': 134,
 '티스': 421,
 '구체': 52,
 '계획': 31,
 '밑그림': 179,
 '그리다': 57,
 '부문': 195,
 '직접': 392,
 '키우다': 409,
 '디지털 역량': 154,
 '역량 지난': 299,
 '지난 과학': 382,
 '과학 종합대학': 40,
 '종합대학 업무': 378,
 '업무 협약': 284,
 '협약 맺다': 485,
 '맺다 데이터': 172,
 '데이터 티스': 135,
 '티스 양성': 422,
 '양성 하다': 279,
 '하다 구체': 438,
 '구체 계획': 53,
 '계획 밑그림': 32,
 '밑그림 그리다': 180,
 '그리다 글로벌': 58,
 '글로벌 부문': 67,
 '부문 인재': 196,
 '인재 직접': 341,
 '직접 키우다': 393,
 '다날': 115,
 '수익': 257,
 '확대': 486,
 '위해': 320,
 '조직': 370,
 '다날 수익': 116,
 '수익 성장': 258,
 '성장 사업': 243,
 '사업 확대': 215,
 '확대 위해': 487,
 '위해 조직': 321,
 '조직 역량': 372,
 '경험': 29,
 '보유': 193,
 '영진': 302,
 '경쟁력': 26,
 '프랜차이즈': 433,
 '재무': 350,
 '구조': 50,
 '가지다': 0,
 '선호': 240,
 '향후': 469,
 '개선': 14,
 '무역': 177,
 '협상': 482,
 '타결': 410,
 '수혜': 259,
 '예상': 304,
 '엔지니어링': 285,
 '경험 역량': 30,
 '역량 보유': 296,
 '보유 영진': 194,
 '영진 경쟁력': 303,
 '경쟁력 프랜차이즈': 27,
 '프랜차이즈 재무': 434,
 '재무 구조': 351,
 '구조 가지다': 51,
 '가지다 기업': 1,
 '기업 선호': 86,
 '선호 하다': 241,
 '하다 향후': 451,
 '향후 글로벌': 470,
 '경기 개선': 23,
 '개선 무역': 15,
 '무역 협상': 178,
 '협상 타결': 483,
 '타결 수혜': 411,
 '수혜 예상': 260,
 '예상 되다': 305,
 '되다 하다': 149,
 '하다 엔지니어링': 443,
 '나오다': 96,
 '네이버': 100,
 '거점': 18,
 '페이스북 나오다': 427,
 '나오다 네이버': 97,
 '네이버 라인': 101,
 '라인 일본': 159,
 '일본 거점': 344,
 '거점 글로벌': 19,
 '글로벌 블록': 68,
 '체인 시장': 398,
 '시장 공략': 266,
 '시대': 261,
 '요구': 312,
 '변화': 191,
 '핵심': 467,
 '끌다': 92,
 '올리다': 306,
 '성장동력': 245,
 '앞서': 274,
 '지난해': 383,
 '대처': 125,
 '경제': 28,
 '기업 시대': 87,
 '시대 요구': 262,
 '요구 하다': 313,
 '하다 변화': 441,
 '변화 대응': 192,
 '하다 위해': 444,
 '위해 핵심': 322,
 '핵심 사업': 468,
 '역량 끌다': 295,
 '끌다 올리다': 93,
 '올리다 하다': 307,
 '하다 사업': 442,
 '사업 투자': 214,
 '투자 성장동력': 420,
 '성장동력 확보': 246,
 '확보 한화': 490,
 '한화 앞서': 462,
 '앞서 지난해': 275,
 '지난해 산업혁명': 384,
 '산업혁명 대처': 227,
 '대처 글로벌': 126,
 '글로벌 경제': 64,
 '발휘': 185,
 '코리아': 407,
 '입증': 348,
 '대표': 127,
 '사례': 205,
 '폴란드': 430,
 '수도': 253,
 '바르샤바': 181,
 '북서쪽': 197,
 '플랜트': 435,
 '김철': 90,
 '코노믹': 406,
 '발휘 코리아': 186,
 '코리아 역량': 408,
 '역량 입증': 298,
 '입증 대표': 349,
 '대표 사례': 128,
 '사례 하다': 206,
 '하다 폴란드': 449,
 '폴란드 수도': 432,
 '수도 바르샤바': 254,
 '바르샤바 북서쪽': 182,
 '북서쪽 석유화학': 198,
 '석유화학 플랜트': 238,
 '플랜트 김철': 436,
 '김철 글로벌': 91,
 '글로벌 코노믹': 73,
 '대구시': 117,
 '네트워크': 102,
 '도시': 136,
 '위상': 316,
 '높이다': 110,
 '대구시 인재': 118,
 '양성 글로벌': 277,
 '글로벌 네트워크': 66,
 '네트워크 강화': 103,
 '강화 로봇': 9,
 '로봇 도시': 162,
 '도시 위상': 137,
 '위상 높이다': 317,
 '현대': 474,
 '글로벌 현대': 74,
 '현대 엔지니어링': 475,
 '엔지니어링 협력': 286,
 '협력 하다': 481,
 '폴란드 석유화학': 431,
 '은행': 334,
 '인력': 336,
 '대적': 123,
 '경쟁': 25,
 '은행 디지털': 335,
 '디지털 글로벌': 153,
 '글로벌 인력': 71,
 '인력 대적': 337,
 '대적 육성': 124,
 '육성 경쟁': 332,
 '서울': 234,
 '종로구': 375,
 '센터': 249,
 '빌딩': 203,
 '연락': 300,
 '개소식': 16,
 '갖다': 12,
 '각국': 2,
 '사이': 220,
 '정책': 363,
 '조율': 367,
 '농림축산식품부': 105,
 '유치': 325,
 '늘다 서울': 112,
 '서울 종로구': 235,
 '종로구 글로벌': 376,
 '글로벌 센터': 69,
 '센터 빌딩': 250,
 '빌딩 한국': 204,
 '한국 협력': 459,
 '협력 연락': 479,
 '연락 사무소': 301,
 '사무소 개소식': 209,
 '개소식 갖다': 17,
 '갖다 협력': 13,
 '사무소 각국': 208,
 '각국 사이': 3,
 '사이 정책': 221,
 '정책 조율': 364,
 '조율 하다': 368,
 '하다 조직': 447,
 '조직 농림축산식품부': 371,
 '농림축산식품부 협력': 106,
 '사무소 유치': 210,
 '유치 농업': 326,
 '농업 식량': 108,
 '선정': 239,
 '대학 교육부': 130,
 '교육부 전문': 48,
 '강화 선정': 10,
 '제조': 365,
 '생산': 230,
 '실무': 272,
 '기능': 75,
 '교육': 43,
 '받다': 183,
 '과정': 37,
 '현장': 476,
 '근무': 59,
 '재직': 352,
 '들이다': 150,
 '내용': 98,
 '진행': 394,
 '돼다': 145,
 '만족도': 168,
 '평가': 428,
 '로봇 제조': 163,
 '제조 생산': 366,
 '생산 실무': 231,
 '실무 전문': 273,
 '전문 기술': 359,
 '기술 기능': 81,
 '기능 교육': 76,
 '교육 역량': 46,
 '강화 교육': 5,
 '교육 받다': 45,
 '받다 교육': 184,
 '교육 과정': 44,
 '과정 산업': 38,
 '산업 현장': 224,
 '현장 근무': 477,
 '근무 하다': 60,
 '하다 재직': 445,
 '재직 들이다': 353,
 '들이다 내용': 151,
 '내용 진행': 99,
 '진행 돼다': 395,
 '돼다 만족도': 146,
 '만족도 평가': 169,
 '평가 글로벌': 429}

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

In [19]:
def get_noun(text):
    tokenizer = Okt()
    nouns = tokenizer.nouns(text)
    return [n for n in nouns]

In [20]:
text_clf_svm = Pipeline([('vect', vectorize),
                         ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=10000, random_state=42))]) # 손실함수 기댓값 최소화

text_clf_svm = text_clf_svm.fit(train["문장"], train["label"])

C:\Users\abcd_\Anaconda3\envs\section2\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)

In [21]:
predicted_svm = text_clf_svm.predict(train["문장"])#학습데이터 테스트
np.mean(predicted_svm == train["label"])

0.14925373134328357

In [22]:
predicted_svm = text_clf_svm.predict(test["문장"])#테스트데이터
np.mean(predicted_svm == test["label"])

0.0

In [23]:
text_clf_svm.predict(["능동적인 사람이 되자"])

array([9], dtype=int64)

In [24]:
X = vectorize.fit_transform(rawdata)
features = vectorize.get_feature_names()

In [25]:
data_array = X.toarray()
data = pd.DataFrame(data_array, columns=features)
data.shape

data = data.rename({0:"글로벌역량", 1:"능동", 2:"도전", 3:"성실", 4:"소통", 5:"인내심", 6:"정직", 7:"주인의식", 8:"창의", 9:"팀워크"}, axis='index')
display(pd.DataFrame(data))

,가끔,가끔 오다,가다,가다 걸리버,가다 고향,가다 기차,가다 되새기다,가다 안병용,가다 위협,가다 하다,...,훈련,훈련 대한,훈련 주장,훈련소,훈련소 입소,휴식,휴식 공간,휴식 소통,희망이,희망이 미래
글로벌역량,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
능동,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
도전,0.000000,0.000000,0.060654,0.065798,0.000000,0.000000,0.000000,0.000000,0.038861,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
성실,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.044849,0.044849,0.000000,0.000000,0.000000,0.000000,0.000000
소통,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.084422,0.040228,0.068111,0.000000,0.000000
인내심,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.072407,0.042765,0.042765,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
정직,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
주인의식,0.000000,0.000000,0.065057,0.000000,0.000000,0.000000,0.041682,0.041682,0.000000,0.041682,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.041682,0.041682
창의,0.065687,0.065687,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
팀워크,0.000000,0.000000,0.052224,0.000000,0.041472,0.041472,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [26]:
text_clf_svm.predict(["능동"])

array([9], dtype=int64)

In [27]:
#0:"글로벌역량", 1:"능동", 2:"도전", 3:"성실", 4:"소통", 5:"인내심", 6:"정직", 7:"주인의식", 8:"창의", 9:"팀워크"
text_clf_svm

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...dom_state=42, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False))])

In [28]:
text_clf_svm.predict(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([8, 9, 9, 9, 9, 9, 9, 9, 9, 9], dtype=int64)

In [30]:
text_clf_svm.decision_function(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([[-1.03723573, -1.03687455, -1.03848077, -1.03589216, -1.03674934,
        -1.03871816, -1.03774213, -1.03238754, -1.03302977, -1.04003548],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574],
       [-0.78622879, -0.78989178, -0.77861365, -0.79492607, -0.78957488,
        -0.77757159, -0.78438175, -0.77325887, -0.76935054, -0.77104574]])